<section class="copyright">
$if(page.property_is.("project.license").("Apache-2.0"))$
    <div>$page.properties.("project.name")$ is Open Source and available under the Apache 2 License.</div>
$endif$
    <p class="legal">
        &copy; 2019-$page.properties.("date.year")$ <a href="https://www.yangbajing.me" target="_blank">羊八井花园.</a> |
        <a href="https://www.github.com/yangbajing" target="_blank">Github：@yangbajing</a> |
        <a href="https://weibo.com/yangbajing" target="_blank">Weibo: @yangbajing</a> |
        <a href="https://www.yangbajing.me/akka-cookbook" target="_blank">《Akka Cookbook》</a>
    </p>
</section>